controller_list:
  - name: hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_12
      - joint_13
      - joint_14
      - joint_15
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - joint_8
      - joint_9
      - joint_10
      - joint_11