controller_list:
  - name: fake_panda_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_allergo_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_12
      - joint_13
      - joint_14
      - joint_15
      - joint_4
      - joint_5
      - joint_6
      - joint_7
      - joint_8
      - joint_9
      - joint_10
      - joint_11
initial:  # Define initial robot poses per group
  - group: panda_arm
    pose: home1
  - group: allergo_hand
    pose: home2