controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - RIQ_palm_RIQ_link_0_joint
      - RIQ_link_0_RIQ_link_1_joint_c
      - RIQ_link_1_RIQ_link_2_joint_c
      - RIQ_link_2_RIQ_link_3_joint_c
      - RIQ_palm_RIQ_link_0_joint_b
      - RIQ_link_0_RIQ_link_1_joint_b
      - RIQ_link_1_RIQ_link_2_joint_b
      - RIQ_link_2_RIQ_link_3_joint_b
      - RIQ_palm_RIQ_link_1_joint_a
      - RIQ_link_1_RIQ_link_2_joint_a
      - RIQ_link_2_RIQ_link_3_joint_a
initial:  # Define initial robot poses per group
  - group: hand
    pose: first