controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - index_finger_joint1
      - index_finger_join2
      - index_finger_joint3
      - index_finger_joint4
      - little_finger_joint1
      - little_finger_joint2
      - little_finger_joint3
      - little_finger_joint4
      - little_finger_joint5
      - middle_finger_joint1
      - middle_finger_joint2
      - middle_finger_joint3
      - middle_finger_joint4
      - ring_finger_joint1
      - ring_finger_joint2
      - ring_finger_joint3
      - ring_finger_joint4
      - thumb_joint1
      - thumb_joint2
      - thumb_joint3
      - thumb_joint4
      - thumb_joint5
initial:  # Define initial robot poses per group
  - group: hand
    pose: pick